//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicsExprHelper.Interop.BizService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SvcRequest", Namespace="http://www.ustcori.com/2009/10")]
    [System.SerializableAttribute()]
    public partial class SvcRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BizCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnableCacheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> ParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BizCode {
            get {
                return this.BizCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BizCodeField, value) != true)) {
                    this.BizCodeField = value;
                    this.RaisePropertyChanged("BizCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnableCache {
            get {
                return this.EnableCacheField;
            }
            set {
                if ((this.EnableCacheField.Equals(value) != true)) {
                    this.EnableCacheField = value;
                    this.RaisePropertyChanged("EnableCache");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodName {
            get {
                return this.MethodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodNameField, value) != true)) {
                    this.MethodNameField = value;
                    this.RaisePropertyChanged("MethodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SvcResponse", Namespace="http://www.ustcori.com/2009/10")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PhysicsExprHelper.Interop.BizService.SvcRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PhysicsExprHelper.Interop.BizService.ResponseStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
    public partial class SvcResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PhysicsExprHelper.Interop.BizService.ResponseStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataString {
            get {
                return this.DataStringField;
            }
            set {
                if ((object.ReferenceEquals(this.DataStringField, value) != true)) {
                    this.DataStringField = value;
                    this.RaisePropertyChanged("DataString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordCount {
            get {
                return this.RecordCountField;
            }
            set {
                if ((this.RecordCountField.Equals(value) != true)) {
                    this.RecordCountField = value;
                    this.RaisePropertyChanged("RecordCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PhysicsExprHelper.Interop.BizService.ResponseStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://www.ustcori.com/2009/10")]
    public enum ResponseStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BadRequest = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownFailure = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ustcori.com/2009/10", ConfigurationName="BizService.IBizService")]
    public interface IBizService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ustcori.com/2009/10/IBizService/DoService", ReplyAction="http://www.ustcori.com/2009/10/IBizService/DoServiceResponse")]
        PhysicsExprHelper.Interop.BizService.DoServiceResponse DoService(PhysicsExprHelper.Interop.BizService.DoServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.ustcori.com/2009/10/IBizService/DoService", ReplyAction="http://www.ustcori.com/2009/10/IBizService/DoServiceResponse")]
        System.IAsyncResult BeginDoService(PhysicsExprHelper.Interop.BizService.DoServiceRequest request, System.AsyncCallback callback, object asyncState);
        
        PhysicsExprHelper.Interop.BizService.DoServiceResponse EndDoService(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ustcori.com/2009/10/IBizService/SyncCMMUser", ReplyAction="http://www.ustcori.com/2009/10/IBizService/SyncCMMUserResponse")]
        PhysicsExprHelper.Interop.BizService.SyncCMMUserResponse SyncCMMUser(PhysicsExprHelper.Interop.BizService.SyncCMMUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.ustcori.com/2009/10/IBizService/SyncCMMUser", ReplyAction="http://www.ustcori.com/2009/10/IBizService/SyncCMMUserResponse")]
        System.IAsyncResult BeginSyncCMMUser(PhysicsExprHelper.Interop.BizService.SyncCMMUserRequest request, System.AsyncCallback callback, object asyncState);
        
        PhysicsExprHelper.Interop.BizService.SyncCMMUserResponse EndSyncCMMUser(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoService", WrapperNamespace="http://www.ustcori.com/2009/10", IsWrapped=true)]
    public partial class DoServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ustcori.com/2009/10", Order=0)]
        public PhysicsExprHelper.Interop.BizService.SvcRequest request;
        
        public DoServiceRequest() {
        }
        
        public DoServiceRequest(PhysicsExprHelper.Interop.BizService.SvcRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoServiceResponse", WrapperNamespace="http://www.ustcori.com/2009/10", IsWrapped=true)]
    public partial class DoServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ustcori.com/2009/10", Order=0)]
        public PhysicsExprHelper.Interop.BizService.SvcResponse DoServiceResult;
        
        public DoServiceResponse() {
        }
        
        public DoServiceResponse(PhysicsExprHelper.Interop.BizService.SvcResponse DoServiceResult) {
            this.DoServiceResult = DoServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncCMMUser", WrapperNamespace="http://www.ustcori.com/2009/10", IsWrapped=true)]
    public partial class SyncCMMUserRequest {
        
        public SyncCMMUserRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncCMMUserResponse", WrapperNamespace="http://www.ustcori.com/2009/10", IsWrapped=true)]
    public partial class SyncCMMUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ustcori.com/2009/10", Order=0)]
        public string SyncCMMUserResult;
        
        public SyncCMMUserResponse() {
        }
        
        public SyncCMMUserResponse(string SyncCMMUserResult) {
            this.SyncCMMUserResult = SyncCMMUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBizServiceChannel : PhysicsExprHelper.Interop.BizService.IBizService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DoServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PhysicsExprHelper.Interop.BizService.DoServiceResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PhysicsExprHelper.Interop.BizService.DoServiceResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SyncCMMUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SyncCMMUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PhysicsExprHelper.Interop.BizService.SyncCMMUserResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PhysicsExprHelper.Interop.BizService.SyncCMMUserResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizServiceClient : System.ServiceModel.ClientBase<PhysicsExprHelper.Interop.BizService.IBizService>, PhysicsExprHelper.Interop.BizService.IBizService {
        
        private BeginOperationDelegate onBeginDoServiceDelegate;
        
        private EndOperationDelegate onEndDoServiceDelegate;
        
        private System.Threading.SendOrPostCallback onDoServiceCompletedDelegate;
        
        private BeginOperationDelegate onBeginSyncCMMUserDelegate;
        
        private EndOperationDelegate onEndSyncCMMUserDelegate;
        
        private System.Threading.SendOrPostCallback onSyncCMMUserCompletedDelegate;
        
        public BizServiceClient() {
        }
        
        public BizServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<DoServiceCompletedEventArgs> DoServiceCompleted;
        
        public event System.EventHandler<SyncCMMUserCompletedEventArgs> SyncCMMUserCompleted;
        
        public PhysicsExprHelper.Interop.BizService.DoServiceResponse DoService(PhysicsExprHelper.Interop.BizService.DoServiceRequest request) {
            return base.Channel.DoService(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDoService(PhysicsExprHelper.Interop.BizService.DoServiceRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoService(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PhysicsExprHelper.Interop.BizService.DoServiceResponse EndDoService(System.IAsyncResult result) {
            return base.Channel.EndDoService(result);
        }
        
        private System.IAsyncResult OnBeginDoService(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PhysicsExprHelper.Interop.BizService.DoServiceRequest request = ((PhysicsExprHelper.Interop.BizService.DoServiceRequest)(inValues[0]));
            return this.BeginDoService(request, callback, asyncState);
        }
        
        private object[] OnEndDoService(System.IAsyncResult result) {
            PhysicsExprHelper.Interop.BizService.DoServiceResponse retVal = this.EndDoService(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDoServiceCompleted(object state) {
            if ((this.DoServiceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoServiceCompleted(this, new DoServiceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoServiceAsync(PhysicsExprHelper.Interop.BizService.DoServiceRequest request) {
            this.DoServiceAsync(request, null);
        }
        
        public void DoServiceAsync(PhysicsExprHelper.Interop.BizService.DoServiceRequest request, object userState) {
            if ((this.onBeginDoServiceDelegate == null)) {
                this.onBeginDoServiceDelegate = new BeginOperationDelegate(this.OnBeginDoService);
            }
            if ((this.onEndDoServiceDelegate == null)) {
                this.onEndDoServiceDelegate = new EndOperationDelegate(this.OnEndDoService);
            }
            if ((this.onDoServiceCompletedDelegate == null)) {
                this.onDoServiceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoServiceCompleted);
            }
            base.InvokeAsync(this.onBeginDoServiceDelegate, new object[] {
                        request}, this.onEndDoServiceDelegate, this.onDoServiceCompletedDelegate, userState);
        }
        
        public PhysicsExprHelper.Interop.BizService.SyncCMMUserResponse SyncCMMUser(PhysicsExprHelper.Interop.BizService.SyncCMMUserRequest request) {
            return base.Channel.SyncCMMUser(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSyncCMMUser(PhysicsExprHelper.Interop.BizService.SyncCMMUserRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSyncCMMUser(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PhysicsExprHelper.Interop.BizService.SyncCMMUserResponse EndSyncCMMUser(System.IAsyncResult result) {
            return base.Channel.EndSyncCMMUser(result);
        }
        
        private System.IAsyncResult OnBeginSyncCMMUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PhysicsExprHelper.Interop.BizService.SyncCMMUserRequest request = ((PhysicsExprHelper.Interop.BizService.SyncCMMUserRequest)(inValues[0]));
            return this.BeginSyncCMMUser(request, callback, asyncState);
        }
        
        private object[] OnEndSyncCMMUser(System.IAsyncResult result) {
            PhysicsExprHelper.Interop.BizService.SyncCMMUserResponse retVal = this.EndSyncCMMUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSyncCMMUserCompleted(object state) {
            if ((this.SyncCMMUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SyncCMMUserCompleted(this, new SyncCMMUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SyncCMMUserAsync(PhysicsExprHelper.Interop.BizService.SyncCMMUserRequest request) {
            this.SyncCMMUserAsync(request, null);
        }
        
        public void SyncCMMUserAsync(PhysicsExprHelper.Interop.BizService.SyncCMMUserRequest request, object userState) {
            if ((this.onBeginSyncCMMUserDelegate == null)) {
                this.onBeginSyncCMMUserDelegate = new BeginOperationDelegate(this.OnBeginSyncCMMUser);
            }
            if ((this.onEndSyncCMMUserDelegate == null)) {
                this.onEndSyncCMMUserDelegate = new EndOperationDelegate(this.OnEndSyncCMMUser);
            }
            if ((this.onSyncCMMUserCompletedDelegate == null)) {
                this.onSyncCMMUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSyncCMMUserCompleted);
            }
            base.InvokeAsync(this.onBeginSyncCMMUserDelegate, new object[] {
                        request}, this.onEndSyncCMMUserDelegate, this.onSyncCMMUserCompletedDelegate, userState);
        }
    }
}
